mymusic/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from music import views
from mymusic import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),




    url(r'^albumler/', views.albumler_page, name='albumler'),
    url(r'^album/(?P<album_title>.+)/(?P<album_id>[0-9]+)', views.album_page, name='album'),



    url(r'^songdetails/(?P<song_name>.+)/(?P<song_id>[0-9]+)' , views.songdetails_page, name='songdetails'),




    url(r'^sarkicilar/', views.sarkicilar_page, name='sarkicilar'),
    url(r'^sarkicilardetails/(?P<singer_name>.+)/(?P<singer_id>[0-9]+)' , views.sarkicilardetails_page, name='sarkicilardetails'),


    url(r'^sarkilar/', views.sarkilar, name='sarkilar'),

    url(r'^roportaj/', views.roportaj, name='roportaj'),

    url(r'^/(?P<roportaj_id>[0-9]+)' , views.roportajdetails_page, name='roportajdetails'),



]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

music/models.py
from django.urls import reverse
from datetime import datetime
from django.db import models
from embed_video.fields import EmbedVideoField



class Album(models.Model):
    genre = models.ForeignKey('Genre')
    singer = models.ForeignKey('Singer')
    topic_author = models.ForeignKey('auth.User')
    album_title = models.CharField(max_length=1000)
    album_logo = models.ImageField(upload_to="music_imgs", blank=True)
    album_date = models.DateField(default=datetime.now(), blank=True)

    def __str__(self):
        return self.album_title

class Song(models.Model):
    album = models.ForeignKey('Album')
    song_name=models.CharField(max_length=1000)
    video = models.CharField(max_length=1000)
    song_point = models.IntegerField()
    song_date = models.DateField(default=datetime.now(), blank=True)
    song_lyrics = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('songdetails', kwargs={'song_name': self.song_name,'song_id' : self.id})


    def __str__(self):
        return self.song_name



class Singer(models.Model):
    singer_foto = models.ImageField(upload_to="music_imgs", blank=True)
    singer_name = models.CharField(max_length=50)
    singer_life = models.TextField(blank=True)

    def __str__(self):
        return self.singer_name

class Comment(models.Model):
        song = models.ForeignKey('Song', on_delete=models.CASCADE, related_name='comments')
        name = models.CharField(max_length=200, verbose_name='Ad Soyad')
        content = models.TextField(verbose_name='Yorum')


        def __str__(self):
            return self.name



class Genre(models.Model):
    genre = models.CharField(max_length=50)

    def __str__(self):
        return self.genre


class Roportaj(models.Model):

    singer = models.ForeignKey('Singer')
    text = models.TextField(blank=True)
    textuzun = models.TextField(blank=True)

music/forms.py
from django import forms
from .models import  Comment






class CommentForm(forms.ModelForm):
    # name = forms.CharField(widget=forms.TextInput(attrs={'class': 'inputfield'}))
    # content = forms.CharField(widget=forms.Textarea(attrs={'class': 'contentClass'}))


    class Meta:
        model = Comment
        fields = [
            'name',
            'content',
        ]

music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from music import models
from music.forms import CommentForm
from .models import Album, Song, Singer, Roportaj


def index(request):
    albums = Album.objects.all().order_by('album_date')[:6]
    singer=Singer.objects.all()
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    context = {"albums" : albums, "song_list" : song_list , "lastest_song" : lastest_song, "singer": singer }

    return render(request, 'music/index.html', context)



def albumler_page(request):
    albums = Album.objects.all()
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    context = {"albums" : albums, "song_list" : song_list, "lastest_song" : lastest_song}

    return render(request, 'music/albumler.html', context)


def album_page(request, album_id, album_title):
    print(album_id, album_title)
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    album = get_object_or_404(Album, pk=album_id)
    context = {"album": album, "song_list" : song_list, "lastest_song" : lastest_song}
    return render(request, "music/album.html", context)



def songdetails_page(request, song_name , song_id):
    print(song_name , song_id)
    song = get_object_or_404(Song, pk=song_id)
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.song = song
        comment.save()
        return HttpResponseRedirect(song.get_absolute_url())

    context = {"song": song, "song_list" : song_list, "lastest_song" : lastest_song,"form":form}
    return render(request, "music/songdetails.html", context)


def sarkicilar_page(request):
    albums = Album.objects.all()
    song_list = Song.objects.all().order_by('song_point')[:15]
    singer = Album.objects.all()
    lastest_song = Song.objects.all().order_by('song_date')[:15]

    context = {"albums" : albums , "song_list" : song_list, "lastest_song" : lastest_song, "singer": singer}
    return render(request, 'music/sarkicilar.html', context)





def sarkicilardetails_page(request, singer_name , singer_id):
    print(singer_name , singer_id)
    albums = Album.objects.all()
    singer = get_object_or_404(Singer, pk=singer_id)
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    context = {"albums" : albums , "singer": singer , "song_list" : song_list, "lastest_song" : lastest_song}
    return render(request, "music/sarkicilardetails.html", context)





def sarkilar(request):
    albums = Album.objects.all()
    song = Song.objects.all()
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    context = {"albums" : albums , "song_list" : song_list, "lastest_song" : lastest_song, "song" : song }
    return render(request, 'music/sarkilar.html', context)



def roportaj(request):
    albums = Album.objects.all().order_by('album_date')[:6]
    roportaj = Roportaj.objects.all()
    singer=Singer.objects.all()
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    context = {"albums" : albums, "song_list" : song_list ,
               "lastest_song" : lastest_song, "singer": singer, "roportaj" : roportaj }

    return render(request, 'music/roportaj.html', context)



def roportajdetails_page(request, roportaj_id):
    print(roportaj_id)
    roportaj = get_object_or_404(Roportaj, pk=roportaj_id)
    song_list = Song.objects.all().order_by('song_point')[:15]
    lastest_song = Song.objects.all().order_by('song_date')[:15]
    context = {"song_list" : song_list, "lastest_song" : lastest_song, "roportaj" : roportaj }
    return render(request, "music/roportajdetails.html", context)

music/templates/music/album.html
{% extends "music/base.html" %}

{% load static %}

{%block title%}
<h1>{{ album.singer_name }} - {{ album.album_title }}</h1>
{% endblock title%}






{% block pages %}

    <div id="templatemo_menu">

     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/">Şarkıcılar</a></li>
            <li><a href="/albumler/" class="current">Albümler</a></li>
            <li><a href="/sarkilar/">Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu">Roportaj</a></li>
        </ul>

    </div>

{% endblock pages %}






{% block album %}
<ul >
<img align=center
     src="/media/{{ album.album_logo }}" width=400 height=400 alt="album_logo"/><br>


    {% for song in album.song_set.all  %}

    <br></be><li><font face="verdana" color="yellow" size="5" >
    <a href="{% url 'songdetails' song.song_name|slugify song.id %}">{{song.song_name}} </a></font></li><br>
    {% endfor %}

</ul>
{% endblock album %}

music/templates/music/albumler.html
{% extends "music/base.html" %}

{% load static %}


{%block title%}
<h1>Albumler</h1>
{% endblock title%}



{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/">Şarkıcılar</a></li>
            <li><a href="/albumler/" class="current">Albümler</a></li>
            <li><a href="/sarkilar/">Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}







{% block album %}
<ul>
    {%for album in albums %}
    <div class="col-sm-6">
        <img align=center src="/media/{{ album.album_logo }}" width=180" height="180" alt="album_logo"/>
        <li><a href="{% url 'album' album.album_title|slugify album.id %}"><h3>{{album.album_title}} </a> </h3></li>
        <h4>{{ album.singer_name}}</h4>
    </div>
    {%endfor%}
</ul>
{% endblock album %}

music/templates/music/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <link href="/static/assets/css/templatemo_style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="/static/assets/css/bootstrap.min.css">
      <link rel="stylesheet" href="/static/assets/css/bootstrap.css">
    <link rel="shortcut icon" href="favicon.ico">


    <link rel="stylesheet" href="/static/assets/css/templatemo_style.css">
    <script src="/static/assets/js/html5.js"></script>
    <script src="/static/assets/js/respond.min.js"></script>







</head>
<body>
<!--
This is a free CSS template provided by templatemo.com
-->





<div id="templatemo_container">

	<div id="templatemo_header">
    	<div id="templatemo_title">
            <div id="templatemo_sitetitle">Müzik <span>Dinle</span></div>
        </div>

        <div class="social" align="right"> <span>Bizi Takip Edin:</span>

        <a class="twitter" href="https://www.twitter.com/">twitter</a>
        <a class="facebook" href="https://www.facebook.com/">facebook</a>
        <a class="youtube" href="https://www.youtube.com/">youtube</a>

        </div>

        <div id="templatemo_login">
        	<form method="get" action="#">
                <label>Ara:</label><input class="inputfield" name="keyword" type="text" id="keyword"/>
                <input class="button" type="submit" name="Ara" value="Ara" />

            </form>



    </div>

    </div>

	<div id="templatemo_banner">


       	<div id="templatemo_banner_text">
		
            <div id="banner_title" align="center">Müzik Dünyasına Hoşgeldiniz!</div>
            
    	</div>
	</div>

	{% block pages %}
	{% endblock pages %}

    <div id="templatemo_content">
    
    	<div id="templatemo_left_column">


            <div class="left_col_box">


                <h2>En Cok Dinlenen Sarkilar</h2>


                <ul>
                    {% for song in song_list %}

                    <li><img src=/media/{{ song.album.singer.singer_foto }} width="25" height="25"><font face="verdana" color="yellow" size="2.2"><a href="{% url 'songdetails' song.song_name|slugify song.id %}">
                     {{song.song_name}}</a></font></li><br>

                    {%endfor%}
                </ul>
                <h2>Yeni Cikan Sarkilar</h2>

                <ul >
                    {%for song in lastest_song %}
                    <li><img src=/media/{{ song.album.singer.singer_foto }} width="25" height="25"><font face="verdana" color="yellow" size="2.2"><a href="{% url 'songdetails' song.song_name|slugify song.id %}">
                        {{ song.song_name }}</a> </font></li><br>

                    {%endfor%}
                </ul>
			</div>

		</div>





      <div id="templatemo_right_column">

        	<div id="new_released_section">
            	{%block title%}
                {% endblock title%}
                {% block album %}
            	<div class="new_released_box">
                {% endblock album %}
              <div class="rantsection">

                    </div>

            </div>

            
		</div>
    </div>
    <!--  Designed by w w w . t e m p l a t e m o . c o m  --> 
    
	<div id="templatemo_footer">
        
        <!-- Credit: www.templatemo.com -->
	</div>
</div>
<!-- templatemo 047 music -->
<!-- 
Music Template 
http://www.templatemo.com/preview/templatemo_047_music 
-->  
</body>
</html>

music/templates/music/comments.html
{% load crispy_forms_tags %}


<form method="POST" style="">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Yorum Ekle">
</form>

music/templates/music/index.html
{% extends "music/base.html" %}

{% load static %}


{%block title%}
<h1>Yeni Cikan Albumler</h1>
{% endblock title%}



{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" class="current">Anasayfa</a></li>
			<li><a href="/sarkicilar/">Şarkıcılar</a></li>
            <li><a href="/albumler/">Albümler</a></li>
            <li><a href="/sarkilar/">Şarkılar</a></li>
           <li><a href="/roportaj/" class="lastmenu">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}








{% block album %}
<ul>
    {%for album in albums %}


    <div class="col-sm-6">

        <img align=center src="/media/{{ album.album_logo }}" width="180" height="180" alt="album_logo"/>
        <br>
        <br>
        <li><a href="{% url 'album' album.album_title|slugify album.id %}"><h3>{{album.album_title}} </a> </h3></li>
        <br>
    </div>

    {%endfor%}
</ul>
{% endblock album %}

music/templates/music/roportaj.html
{% extends "music/base.html" %}

{% load static %}


{%block title%}
<h1>Roportajlar</h1>
{% endblock title%}



{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/">Şarkıcılar</a></li>
            <li><a href="/albumler/" >Albümler</a></li>
            <li><a href="/sarkilar/">Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu" class="current">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}







{% block album %}

    {%for roportaj in roportaj %}
    <table border="3">
         <tr>
             <td> <img align=center src="/media/{{ roportaj.singer.singer_foto }}" width="150" height="150"/></td>

                <td>
                    <h3> {{roportaj.singer.singer_name}}  ile Roportaj </h3>
                    <p><font size="2.5"> <a href="{% url 'roportajdetails' roportaj.id %}" >{{ roportaj.text }}</a> </font></p>

                </td>


         </tr>

        <br>
        <br>
    </table>

    {% endfor %}
{% endblock album %}

music/templates/music/roportajdetails.html
{% extends "music/base.html" %}

{% load static %}


{%block title%}
<h1>{{roportaj.singer.singer_name}}  ile Roportaj</h1>
{% endblock title%}



{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/" >Şarkıcılar</a></li>
            <li><a href="/albumler/">Albümler</a></li>
            <li><a href="/sarkilar/">Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu" class="current">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}



{% block album %}


<img align="center" src="/media/{{ roportaj.singer.singer_foto }}" width="400" height="400"  />

<br>
<br>

<hr>



<pre> {{ roportaj.textuzun }} </pre>

{% endblock album %}

music/templates/music/sarkicilar.html
{% extends "music/base.html" %}

{% load static %}


{%block title%}
<h1>Sarkicilar</h1>
{% endblock title%}



{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/" class="current">Şarkıcılar</a></li>
            <li><a href="/albumler/">Albümler</a></li>
            <li><a href="/sarkilar/">Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}


{% block album %}

    {%for album in albums %}
    <div class="col-sm-6">
        <img align=center src="/media/{{ album.singer.singer_foto }}" width=180  height="180 " alt="album_logo"/>
        <br>


        <br>


        <h4><a href="{% url 'sarkicilardetails' album.singer.singer_name|slugify album.singer.id %}">
            {{ album.singer.singer_name }}</a></h4>
        <br>
    </div>
    {%endfor%}

{% endblock album %}

music/templates/music/sarkicilardetails.html
{% extends "music/base.html" %}

{% load static %}


{%block title%}
<h1>{{ singer.singer_name }}</h1>
{% endblock title%}



{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/" class="current">Şarkıcılar</a></li>
            <li><a href="/albumler/">Albümler</a></li>
            <li><a href="/sarkilar/">Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}



{% block album %}
<ul >
<img align="center"
     src="/media/{{ singer.singer_foto}}" width=500 height=500 alt="album_logo"/><br>

    <br>
    <br>
    <h1>Hakkinda Bilgi;</h1>
    <br>
    <pre>{{ singer.singer_life }}</pre>

</ul>
{% endblock album %}

music/templates/music/sarkilar.html
{% extends "music/base.html" %}

{% load static %}


{%block title%}
<h1>Sarkilar</h1>
{% endblock title%}



{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/">Şarkıcılar</a></li>
            <li><a href="/albumler/" >Albümler</a></li>
            <li><a href="/sarkilar/" class="current" >Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}



{% block album %}



    {%for album in albums %}
    <table>
         <tr>
             <td> <img align=center src="/media/{{ album.album_logo }}" width="60" height="60" alt="album_logo"/></td>


                {% for song in album.song_set.all  %}
                <td>
                    {% if song.id|divisibleby:3 == 1 %}

                    <font face="verdana" color="pink" size="4" ><a href="{% url 'songdetails' song.song_name|slugify song.id %}">{{song.song_name}} </a>
                    </font> </font>
                    {% endif %}

                </td>

                {% endfor %}
                <td>
                 <font face="verdana" color="blue" size="4" ><a href="{% url 'sarkicilardetails' album.singer.singer_name|slugify album.singer.id %}">
                  -  {{ album.singer.singer_name }}</a></font>
                </td>


         </tr>
    </table>
    {% endfor %}




{% endblock album %}

music/templates/music/songdetails.html
{% extends "music/base.html" %}


{% load static %}

{%block title%}
<h1>{{song.album.singer.singer_name}} - {{ song.album.album_title}} </h1>
{% endblock title%}

{% block pages %}
    <div id="templatemo_menu">
     	<ul>
			<li><a href="/" >Anasayfa</a></li>
			<li><a href="/sarkicilar/">Şarkıcılar</a></li>
            <li><a href="/albumler/">Albümler</a></li>
            <li><a href="/song" class="current">Şarkılar</a></li>
            <li><a href="/roportaj/" class="lastmenu">Roportaj</a></li>
        </ul>
    </div>
{% endblock pages %}



{% block album %}

<iframe width="560" height="315" src="https://www.youtube.com/embed/{{ song.video }}"
        frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>


        <br>
        <br>

<font face="verdana" color="yellow" size="5" > {{ song.song_name }}  Sarki Sozu ; </font>
<br>
<br>
<br>
<pre> {{ song.song_lyrics }}</pre>
  <h3>Yorum Ekle:</h3>
<p>
    {% include 'music/comments.html' %}</p>
                <hr/>

                <h3>Yorumlar:</h3>
                {% for comment in song.comments.all %}
                    <h4>{{ comment.name }}  <small> </small></h4>
                    <p>{{ comment.content|linebreaks }}</p>
                    <hr>
                {% endfor %}

{% endblock album %}